### ISSUE TITLE
[ally.fix.pointerFocusChildren] workaround is not solving the browser's problem

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/ally.js#103]
*Concerning*: [ally.fix.pointerFocusChildren](https://github.com/medialize/ally.js/blob/master/docs/api/fix/pointer-focus-children.md)
*User Agent:* IE11
*ally.js version*: 1.1.0-beta.3

---

## Steps to reproduce the problem

run the demo

## What is the expected behavior?

the workaround works

## What went wrong?

the workaround fails

## Comments

As of 1.0.0 ally.js identifies elements with flexbox layout as focusable (to comply with the browser focus compatibility tables). That makes `get/focus-target` return the `<span>`. While that's correct from a global perspective, it's not what `fix/pointer-focus-children` expects and thus does not redirect focus to the parent element.

Also, maybe we should rename `fix/pointer-focus-children` to `fix/focus-flexbox` or something? But that would be a breaking change and demand a major version bump, according to semver. @marcysutton what do you think?

**Comment by marcysutton** [comment]
This reminds me of propagation problems with click handlers on a tree of elements...could you hijack an event and force focus to go to `event.currentTarget`? 

I agree that a fix for flexbox only might benefit from a more specific name, but who knows if this issue will manifest in some other context....I'd probably avoid the breaking name change and leave that part as-is.

**Comment by rodneyrehm** [comment]
> could you hijack an event and force focus to go to event.currentTarget? 

I don't see how (but that doesn't mean it's not possible…)
