### ISSUE TITLE
MutationObserver does not see changes within a shadow-root

### ISSUE THREAD

**Issue by jordanaustin** [medialize/ally.js#110]
Currently the MutationObserver cannot observe changes within a shadow-root unless explicitly set on the fragment. This is a problem for features like maintain.disabled where we observe changes on a context and filtered elements. As of right now any changed made to those shadow-roots will not be observed. 

The purposed solution suggested by @rodneyrehm on #107 is to check for a shadow-root on all child elements of the context/filters and hookup an observer on all of the shadow-roots individually.

**Comment by jordanaustin** [comment]
I can take this bug on.

**Comment by rodneyrehm** [comment]
Since we need this kind of utility in mutliple places (at least 2), it makes sense to create some sort of abstraction (I called these things "service") for "recursive MutationObservers".

**Comment by jordanaustin** [comment]
Yeah a service to handle this would be a good idea. I'll look at how you've handled services and work on one for this.

**Comment by rodneyrehm** [comment]
First, I don't think we need to observe shadows for `maintain/hidden` after all.

Registering a `MutationObserver` for each *existing* ShadowHost is not a problem upon engaging. Finding ShadowHosts *existing* upon an observed mutation is not a problem either. But we can't observe a mutation when `element.createShadowRoot()` is called, as [this bin](http://jsbin.com/foxiwulola/edit?html,js,console,output) shows.

**Comment by jordanaustin** [comment]
Good findings, thanks for following up on this.

**Comment by rodneyrehm** [comment]
@jordanaustin are you still planning on giving this a shot, or should I take over? If you're up for it, I'm happy to help with docs and tests… I'd be looking to close this soon, as it's one of two remaining issues for the 1.1.0 release.

---

I guess I'd have created `ally/query/shadows` that uses a TreeWalker to find ShadowHosts, much like [query/focusable.strict.js](https://github.com/medialize/ally.js/blob/master/src/query/focusable.strict.js) does. Considering a TreeWalker takes a context, the same function can be used to scan `maintain/disabled`'s engaging context and scan the added nodes identified by MutationObserver. I would probably try extracting the MutationObserver from `maintain/disabled` to `observe/shadows` - a new service that has the a similar surface API to MutationObserver, but also observes any ShadowHosts nested in the engaging context.

**Comment by jordanaustin** [comment]
@rodneyrehm sorry I've been slammed and haven't had a chance to look into this recently. If you have time to take it, that won't hurt my feelings. Otherwise I might have a chance to get back to this in a few weeks. 

I am keenly interested in seeing a 1.1.0 release however so if this is holding it up I can try to carve some time out over the weekend possibly.

**Comment by rodneyrehm** [comment]
No need to apologize… this is OSS, not your dayjob ;) I'll take over :)

**Comment by jordanaustin** [comment]
Thanks @rodneyrehm :)
