### ISSUE TITLE
Error thrown when platform.js does not detect the OS

### ISSUE THREAD

**Issue by jordanaustin** [medialize/ally.js#117]
We build a ChromeOS application but platform.js does not detect ChromeOS, so platform.os.family is null. This causes an issue in util/platform.js since .slice() cannot be called on null.

**Comment by rodneyrehm** [comment]
ChromeOS not being detected should probably be upstreamed to [platform.js](https://github.com/bestiejs/platform.js), if you need that information elsewhere. #118 fixing the null reference is not a bad idea though :)
