### ISSUE TITLE
Implement `focus/within` to "polyfill" CSS Selectors Level 4 `:focus-within` pseudo class

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/ally.js#12]
[`:focus-within`](http://dev.w3.org/csswg/selectors-4/#the-focus-within-pseudo) is a state set on the element having `:focus` and on all ancestor elements (piercing through ShadowDOM).

We can mimic that pseudo-class with the class `.ally-focus-within`, which is added and removed upon `document.activeElement` changing (determined by `focus` event).

**Comment by rodneyrehm** [comment]
published in v0.0.2

**Comment by nuxodin** [comment]
Would a "target-within" be useful too?

**Comment by rodneyrehm** [comment]
In theory yes. I'm not sure what you would want to use it for, though. It is not part of CSS Selectors Level 4, but you can propose it: [www-style@w3.org](mailto:www-style@w3.org?subject=%5Bselectors%5D%20feedback), be sure to add a concrete use-case or expect to be ignored…
