### ISSUE TITLE
Reducing the overall file size of ally.min.js

### ISSUE THREAD

**Issue by t-kelly** [medialize/ally.js#136]
Is there any way of reducing the overall file size of `ally.min.js`? I'm considering this library for a project but 130kb is rather large for a helper library. Is there a way to customize the build to only include the functions needed, similar to lodash?

**Comment by rodneyrehm** [comment]
Have you seen the [getting started](http://allyjs.io/getting-started.html) guide for using modules? ally.js supports [ES6](http://allyjs.io/getting-started.html#Using-ES6-modules), [CommonJS](http://allyjs.io/getting-started.html#Using-CommonJS-modules), [AMD](http://allyjs.io/getting-started.html#Using-AMD-modules).

If you want a distributable version like `ally.min.js`, you can remove modules you don't need from [src/ally.js](https://github.com/medialize/ally.js/blob/master/src/ally.js), and remove individual modules form the namespaces, such as [src/maintain/_maintain.js](https://github.com/medialize/ally.js/blob/master/src/maintain/_maintain.js) before running `npm run build`.

I'd love to see a tool like [jQuery Builder](http://projects.jga.me/jquery-builder/) for ally.js - but I'll leave that to be built by the community for now…

**Comment by t-kelly** [comment]
Thanks for the prompt responses! Total oversight on my end - missed the part about importing individual modules and not the entire library.
