### ISSUE TITLE
ally.maintain.disabled - keyboard appears for a moment on iOS when fired

### ISSUE THREAD

**Issue by mikeebee** [medialize/ally.js#139]
I used `ally.maintain.disabled` to isolate focus when I opened an off-canvas navigation. 

On iOS (9.1.2) I noticed that when I opened the nav, the keyboard appeared for a moment BUT only the first time, closing and re-opening is fine.

This also occurs when you click "toggle inert" on the ally.maintain.disabled example on allyjs.io

**Comment by rodneyrehm** [comment]
> On iOS (9.1.2) I noticed that when I opened the nav, the keyboard appeared for a moment BUT only the first time, closing and re-opening is fine.

If this only happens *once* (and then again *once* only after `localStorage.clear()` and a reload), it's related to the [supports tests](https://github.com/medialize/ally.js/tree/master/src/supports).

If you decouple the call to `ally.maintain.disabled` from user input, you should not see thae OSK (OnScreenKeyboard) showing up. See [test case](http://jsbin.com/kuqotugoba/edit?html,js,output)

**Comment by mikeebee** [comment]
Decoupling did the trick just fine, thanks!

**Comment by ryan-ludwig** [comment]
Can you think of any way to avoid having the keyboard pop up during the supports tests? We're using ally within a packaged Cordova app and every time the app is opened the keyboard pops up for a second.

**Comment by florianbrinkmann** [comment]
Just wanted to add that this can cause page zooming after clicking (here is a test case https://jsfiddle.net/florianbrinkmann/5meew81n/2/), but the trick with `setTimeout`  fixes that, too.
