### ISSUE TITLE
Bootstrap Modal - ally.maintain.tabFocus

### ISSUE THREAD

**Issue by joe-watkins** [medialize/ally.js#145]
Having an issue getting `ally.maintain.tabFocus` to work with Bootstrap 3.0 modal.

As you can [see in this demo](http://codepen.io/joe-watkins/pen/RWzmjJ) everything else appears to be working but not able to handle `tab` `shift-tab` to keep focus out of UI.

Bootstrap [offers open and close events](http://getbootstrap.com/javascript/#modals-events) to hook onto `shown.bs.modal` and `hidden.bs.modal`. 

Any ideas why this isn't working?

[http://codepen.io/joe-watkins/pen/RWzmjJ](http://codepen.io/joe-watkins/pen/RWzmjJ)

**Comment by rodneyrehm** [comment]
[ally.maintain.tabFocus](http://allyjs.io/api/maintain/tab-focus.html) was added in version 1.1.0, but your pen was using version 1.0.1. I've [forked your pen](http://codepen.io/rodneyrehm/pen/jAQbOO) and upraded it to v1.1.1 - works fine for me.

**Comment by joe-watkins** [comment]
@rodneyrehm you rock! Thanks for your work on this tool.
