### ISSUE TITLE
How come visible area does not test for visibility=hidden in parents, etc?

### ISSUE THREAD

**Issue by bluejamesbond** [medialize/ally.js#152]

**Comment by rodneyrehm** [comment]
What *exactly* seems to be the problem? What is happening? What do you expect to happen?

**Comment by bluejamesbond** [comment]
Not sure if it's a problem. But when I tested for visible area on a component whose parent has visibility=hidden, then the function returned > 0

**Comment by rodneyrehm** [comment]
The visual area utility only concerns itself with an element's dimensions and position relative to the viewport. It does not make sure the element is actually *visible*. It could be *invisible*, e.g. via `opacity: 0` or `visibility: hidden`. In either case the element retains its dimensions.

So no, this is not a bug. You're welcome to send a PR adding an appropriate notice to [`when/visible-area.md`](https://github.com/medialize/ally.js/blob/master/docs/api/when/visible-area.md) :)

**Comment by rodneyrehm** [comment]
But if you need to make sure that content is also *visible* when it's in the viewport, you could nest them:

```js
var handle = ally.when.visibleArea({
  context: '#element-to-focus',
  callback: function(element) {
    if (!ally.is.visible(element)) {
      return false;
    }

    console.log('element is visible', element);
  },
});
```
