### ISSUE TITLE
support tests may cause page to scroll

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/ally.js#60]
When ally.js is loaded for the first time (or does not have a cache yet), it runs a batch of [supports](http://allyjs.io/api/supports.html) tests to identify browser compatibility. It caches the results in `localStorage` so it doesn't have to re-run the tests over and over again. That's why this issue hasn't cropped up before.

As part of the tests a few DOM elements are created, injected into the document and focused. Of course they're removed and the previously focussed element becomes the activeElement again. But those focus() calls make the browser **scroll the element into view**.

That means a first-time visitor may end up at the end of the page without having scrolled there. Or in allyjs.io's case, the JSBin iframe containing the example is scrolled into view.

We can solve the scroll position of the document ally.js is loaded in, but I don't see how that would (easily, seamlessly) work with cross-origin iframes.

Anyway, saving the scrollPosition when saving the [currently focused element](https://github.com/medialize/ally.js/blob/154f7e9/src/supports/detect-focus.js#L26) and restoring to that position after the test should do the trick. Since we're appending to `<body>` we should not need to care about nested scrollable containers.

**Comment by ginader** [comment]
:+1:

**Comment by rodneyrehm** [comment]
while touching this component we should also transform all tests to return a function instead of the test result. this allows running the tests when they're actually needed, not when the ally.js source is loaded (identified by #85)
