### ISSUE TITLE
Should ally.js support older browsers?

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/ally.js#71]
Browser support as of ally.js 1.0.1:

> ally.js has been tested on IE10+, Android 4.4+ and iOS8+ alongside the latest desktop versions of Firefox, Chrome and Safari.

For me and my projects that's good enough. For future jQueryUI that is good enough, but for *current* jQuery to use ally.js we'd have to support IE8+.

This issue is here to collect *your* thoughts on the minimum browser version (specifically IE, but also Android WebView and iOS Safari) that ally.js should support. We're trying to assess where we should focus development time…

Simply comment with "IE8", "IE9", "IE10" (which means no change). If you see any other browsers (like [UC Browser](http://www.ucweb.com/ucbrowser/) or [Yandex Browser](https://browser.yandex.com/)) in need of special attention, call for it.

**Comment by ginader** [comment]
Did you run your tests against the mentioned Browsers just to see where we're at? Maybe it's not "a whole lot" of extra work? Is it?

**Comment by rodneyrehm** [comment]
> Did you run your tests against the mentioned Browsers just to see where we're at? Maybe it's not "a whole lot" of extra work? Is it?

not yet. not a bad idea, why did I not think of that?

**Comment by ginader** [comment]
:+1:

**Comment by braders** [comment]
"IE8"

To clarify, I don't mind if features don't necessarily work, but the library should degrade gracefully so that I can use ally.js and not worry about it breaking other scripts on older browsers. No fatal errors should be thrown. 

I guess it would also be good to highlight in the docs any exceptions to the general browser support for each feature/ component.

**Comment by rodneyrehm** [comment]
> To clarify, I don't mind if features don't necessarily work, but the library should degrade gracefully so that I can use ally.js and not worry about it breaking other scripts on older browsers. No fatal errors should be thrown. 

@braders: How would you make an ES5 library not fail in an ES3 browser (without including the ES5shim) though? Simply overwrite all `ally.*` functions with no-ops?

> I guess it would also be good to highlight in the docs any exceptions to the general browser support for each feature/ component. 

@braders: Are [ally.is.focusRelevant notes](http://allyjs.io/api/is/focus-relevant.html#Notes) and [ally.maintain.disabled notes](http://allyjs.io/api/maintain/disabled.html#Notes) examples of that, or did you have something else in mind?

**Comment by braders** [comment]
> How would you make an ES5 library not fail in an ES3 browser (without including the ES5shim) though? Simply overwrite all ally.* functions with no-ops?

I'm thinking basic feature detection - If functions are used that simply don't exist in IE < 8 then break out of the relevant function. Something like
```
if( ! 'querySelector' in document) {
     return
}
//run the function in modern browsers
```
> I guess it would also be good to highlight in the docs any exceptions to the general browser support for each feature/ component.

Exactly like that - Didn't notice that earlier. Great job.

**Comment by rodneyrehm** [comment]
> I'm thinking basic feature detection - If functions are used that simply don't exist in IE < 8 then break out of the relevant function […]

I know the concept (and `ally.maintain.disabled` is doing that in case of MutationObserver on IE10). But since *everything* requires ES5, I would have to break out of *everything*, rendering the library completely useless on ES3 (… but not throwing any errors).

**Comment by braders** [comment]
I've actually just noticed 'ES5-shim' is listed as an implict dependency on the readme. I've not seen it mentioned on the website though (might have missed it). Maybe it should be?

Sounds like it would be a big effort to add ie8 + 9 support without the polyfill though and I can't see people much caring as long as it works if the polyfill in place.

**Comment by rodneyrehm** [comment]
> I've actually just noticed 'ES5-shim' is listed as an implict dependency on the readme. I've not seen it mentioned on the website though (might have missed it). Maybe it should be?

I guess [Getting started](http://allyjs.io/getting-started.html) is a good place to repeat the "system requirements"…

> Sounds like it would be a big effort to add ie8 + 9 support without the polyfill though and I can't see people much caring as long as it works if the polyfill in place.

The ES5 shim is only necessary for IE8 ([ES5 compat table](http://kangax.github.io/compat-table/es5/)).

**Comment by braders** [comment]
:+1: Sounds good

**Comment by rodneyrehm** [comment]
I've started looking at adding support for IE9 in the branch [issue/71-support-ie9](https://github.com/medialize/ally.js/tree/issue/71-support-ie9). At this point the ally.js is fully functional in IE9 (as in all tests are green). The file size rose from 79K to 82K (gzipped 19K to 20K). `ally.is.focusable` shows 4 false positives for `<object>` and `<keygen>` (which still needs fixing).

**Comment by rodneyrehm** [comment]
As discussed in #112 we've made sure that ally.js can be *loaded* in IE8. *executing* any of the methods is a different story. Since [Intern](https://theintern.github.io/) does not run on IE8, we have no way of verifying the libraries integrity on that browser.

Other than Adding full support for IE9 and loading support for IE8, we've switched UA sniffing from browser to rendering engine, in the hopes to catch more things on android browsers - which we are currently *not* testing automatically.

**Comment by mgol** [comment]
Since you mentioned jQuery - we've just rekeased jQuery 1.12 supporting IE6+ & 2.2 supporting IE9+. Those will be the last releases in the 1.x/2.x lines, we're now preparing for a jQuery 3.0 release that will only support IE9+. We're officially ending jQuery IE8- support.

**Comment by rodneyrehm** [comment]
Thanks for the heads up @mgol, much appreciated!
