### ISSUE TITLE
Errors with Ally 1.0.1

### ISSUE THREAD

**Issue by PhiLhoSoft** [medialize/ally.js#85]
Maybe I miss something trivial.
I try to add Ally to an AngularJS 1.x project.
I added it to our `bower.json` file:
		`"ally.js": "https://github.com/medialize/ally.js/releases/download/1.0.1/ally.js.zip",`
(Found it on repository, but it fetches the source, there is no built version there.)
I added it to the `index.hml` file:
`<script src="assets/libs/ally.js/ally.min.js"></script>`
and to `karma.conf.js` too:
`'src/main/webapp/assets/libs/ally.js/ally.min.js',` (in the `files` array).

When I run the tests (not using Ally in the code yet), I get an error:
```
PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'o.bind(r)')
  at C:/Sources/project/.../src/main/webapp/assets/libs/ally.js/ally.min.js:4
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.142 secs / 0 secs)
```
When I load the page in Chrome, I get another error:
```
Uncaught TypeError: Cannot read property 'appendChild' of null
o @ detect-focus.js:18
n.default @ detect-focus.js:44
r.64../detect-focus @ focus-invalid-tabindex.js:6
o @ _prelude.js:1
(anonymous function) @ _prelude.js:1r.28
.../supports/focus-invalid-tabindex @ valid-area.js:43
o @ _prelude.js:1
(anonymous function) @ _prelude.js:1r.82
.../is/valid-tabindex @ sort-elements-by-tabindex.js:50
o @ _prelude.js:1
(anonymous function) @ _prelude.js:1r.3
.../is/native-disabled-supported @ disabled.js:127
o @ _prelude.js:1
(anonymous function) @ _prelude.js:1r.2
../disabled @ ally.js:38o @ _prelude.js:1
(anonymous function) @ _prelude.js:1r.1
../element/_element @ _prelude.js:1
o @ _prelude.js:1
e @ _prelude.js:1
(anonymous function) @ _prelude.js:1
(anonymous function) @ _prelude.js:1
(anonymous function) @ _prelude.js:1
```
I might try another version, just in case, but I have to go right now...

**Comment by rodneyrehm** [comment]
PhantomJS 1.x isn't fully ES5 compatible, as far as I remember. Specifically it's missing `Function.prototype.bind` (which [phantomjs-polyfill](https://www.npmjs.com/package/phantomjs-polyfill) covers). PhantomJS 2 fixed that (according to [ES5 compat table](http://kangax.github.io/compat-table/es5/#phantom)).

The second error, the one where Chrome is saying that `Uncaught TypeError: Cannot read property 'appendChild' of null` refers to the following line `document.body.appendChild(wrapper);`. This indicated that you're running the script synchronously in `<head>` (before the opening `<body>` was parsed).

Quick fixes: For the PhantomJS problem I'd try the polyfill. For the Chrome issue I'd try [`<script defer>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer).

The issue you saw in Chrome would likely disappear after fixing #60 (which is already on the roadmap for the next major release)

**Comment by PhiLhoSoft** [comment]
Sorry for the typo in the title, sometime my fingers type something else than what I wanted... :smile: 

Indeed, I have meet this bind error earlier, since then I just use Lodash's bind or partial... (mmm, might be another part of the proposed Lodash refactoring...).

I fear we are more or less stuck with this version of PhantomJS, as it comes with Karma which we use in our AngularJS project... But the hint on the polyfill seems worth investigating, thanks!

And, yes, the scripts are in `head`, for legacy reasons (I personally always put them at the end of `body`). Either I will just change that, or will use your `defer` trick.

Thanks for the quick answer and help.
I will close the issue as soon as I confirmed the problems are gone.

**Comment by PhiLhoSoft** [comment]
OK, the problems are gone, even if I haven't tried Ally for real yet.
For the record, even if it seems obvious retrospectively, the polyfill must be loaded before Ally... :smile: (the test dependencies were grouped just before the test files themselves in the karma conf file; now, I need some before, and some others (like syn) after the other scripts).

Closing now.
