### ISSUE TITLE
Travis is not building PRs from forked repositories

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/ally.js#95]
Because of [Security Restrictions when testing Pull Requests](https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests) Travis won't export the secret tokens to the build script. That prevents Intern from connecting to BrowserStack and thus fail the build. This just happened in #94 ([Build #163](https://travis-ci.org/medialize/ally.js/builds/98165723)).

The Travis docs advise to simply not run the build scripts requiring secret tokens:

```sh
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && _your_build_command_ || false'
```

At this time ally.js simply runs the test suite on BrowserStack and publishes a few results to CodeClimate and Coveralls - all of which require tokens for authentication. Without the tokens we *could* run the npm scripts `lint`, `build` and `build:website`. I'm not sure how useful that is by itself.

There was a discussion about how to solve this properly: travis-ci/travis-ci#1946. Of course nothing came of it. Instead of going with [Jörn's idea](https://github.com/travis-ci/travis-ci/issues/1946#issuecomment-55500556), *nothing* has happened. I'm not sure I can stress the following enough: instead of being able to use a potentially insecure solution (but somewhat traceable, when breached), projects like Angular now simply [expose their tokens in plain text](https://github.com/angular/angular.js/blob/master/.travis.yml#L25-L26). What a big win for Travis' Security Department.

How do we fix this? I'm reluctant to follow Angular's suit. Maybe it's time to replace Travis with something else? I've heard good things about [drone.io](http://drone.io/).

**Comment by jzaefferer** [comment]
For QUnit I went with a slightly more obscure variation of plain text: https://github.com/jquery/qunit/blob/master/.travis.yml#L7-L8 - its not hard to decode, but at least it won't show up when searching for "BROWSERSTACK_KEY" or something like that.

Since that Travis issue is still open, but locked, I don't know what to do there.

Another CI service I've heard about, also offering GitHub integration: https://circleci.com/

**Comment by rodneyrehm** [comment]
https://github.com/travis-ci/travis-ci/issues/5579#issuecomment-180805112 cc @jzaefferer
