### ISSUE TITLE
docs: Ember-cli integration

### ISSUE THREAD

**Issue by jmacqueen** [medialize/ally.js#96]
I'm not sure if this is the best way to let you (and others) know or not, but I have made a little addon to wrap ally.js for ember-cli use. I needed it for my work and just want folks to know it's available via the main npm repository as `ember-cli-ally` if anyone else has a need.

[npm link](https://www.npmjs.com/package/ember-cli-ally) and [repo link](https://github.com/jmacqueen/ember-cli-ally)

**Comment by rodneyrehm** [comment]
nice!

I've never used ember, nor do I know what ember-cli is, but don't you need to actually load ally.js somewhere? your [package.json](https://github.com/jmacqueen/ember-cli-ally/blob/master/package.json) doesn't mention it and I'm not sure what [vendor/shims/ally.js](https://github.com/jmacqueen/ember-cli-ally/blob/master/vendor/shims/ally.js) is supposed to do…

**Comment by jmacqueen** [comment]
The main function of the addon is to instruct the importing `ember-cli` project on how to add `ally.js` (which happens [here](https://github.com/jmacqueen/ember-cli-ally/blob/master/blueprints/ember-cli-ally/index.js#L13-L15)) and then to expose the `ally.js` global namespace in a way that it can be used with the same ES6 syntax employed elsewhere in `ember-cli` projects (which is the purpose of [vendor/shims/ally.js](https://github.com/jmacqueen/ember-cli-ally/blob/master/vendor/shims/ally.js)).

The addon itself doesn't have to contain `ally.js`. It is included in the `bower.json` so that I can add some tests to the package at a later time, though.

**Comment by rodneyrehm** [comment]
It's starting to make sense to me, thank you for the explanation!

One last question, why is the [afterInstall](https://github.com/jmacqueen/ember-cli-ally/blob/master/blueprints/ember-cli-ally/index.js#L13-L15) loading things off bower? Is that an ember convention? wouldn't it make more sense to load the package through npm? That way you'd get informed of new versions more easily, no?

**Comment by jmacqueen** [comment]
The short answer is, "it's an Ember-cli convention." Which makes it a de-facto Ember convention at this point. Currently, browser-side dependencies are managed with bower when using `ember-cli`. There's some talk about moving to `npm` with Browserify or webpack, but that's not the current state of play.

It would be great if you registered your repo with bower. The name `ally` is taken, but `ally-js` and `ally.js` are available. And then, all you need is to use semver style tags for your releases, which you're already doing anyway :smile:

http://bower.io/docs/creating-packages/
https://github.com/bower/spec/blob/master/json.md

**Comment by rodneyrehm** [comment]
> It would be great if you registered your repo with bower. The name ally is taken, but ally-js and ally.js are available. And then, all you need is to use semver style tags for your releases, which you're already doing anyway

If bower wouldn't force me to commit *build artifacts* to my repository, I'd have continued to supply versions of ally.js to it. The repo is still registered, as `bower info ally.js` will show. But all you get through that is the ES6 source - no AMD, CommonJS or UMD:

```
➜  bower install ally.js && du -sh bower_components/ally.js && tree -L 3 bower_components
bower ally.js#*                 cached git://github.com/medialize/ally.js.git#1.0.1
bower ally.js#*               validate 1.0.1 against git://github.com/medialize/ally.js.git#*
3.9M	bower_components/ally.js
bower_components
└── ally.js
    ├── CHANGELOG.md
    ├── CONTRIBUTING.md
    ├── GOALS.md
    ├── LICENSE.txt
    ├── README.md
    ├── build
    │   ├── build.archive.js
    │   ├── build.post.js
    │   ├── build.pre.js
    │   ├── data-tables
    │   ├── markdownlint.js
    │   ├── metalsmith
    │   ├── publish.website.js
    │   └── web-tests
    ├── docs
    │   ├── README.md
    │   ├── api
    │   ├── concepts.md
    │   ├── contributing
    │   ├── data-tables
    │   ├── getting-started.md
    │   ├── questions.md
    │   ├── tutorials
    │   └── what-is-focusable.md
    ├── issues.md
    ├── package.json
    ├── resources.md
    ├── src
    │   ├── ally.js
    │   ├── element
    │   ├── event
    │   ├── fix
    │   ├── get
    │   ├── is
    │   ├── maintain
    │   ├── map
    │   ├── observe
    │   ├── prototype
    │   ├── query
    │   ├── selector
    │   ├── style
    │   ├── supports
    │   ├── util
    │   ├── version.js
    │   └── when
    ├── test
    │   ├── browser.js
    │   ├── browserstack.js
    │   ├── functional
    │   ├── helper
    │   ├── intern.base-config.js
    │   ├── local.js
    │   ├── pages
    │   ├── run-local.js
    │   ├── sauce.js
    │   └── unit
    └── tests
        ├── browser-bugs
        ├── event-sequence
        ├── exploring
        ├── focus-outline-styles
        ├── focusable
        ├── fragment-focus
        ├── index.html
        ├── media
        └── scrolling

40 directories, 27 files
```

here's what you get from npm:

```
➜  npm install ally.js && du -sh node_modules/ally.js && tree -L 2 node_modules
ally.js@1.0.1 node_modules/ally.js
├── css.escape@1.4.0
├── platform@1.3.0
└── array.prototype.findindex@1.0.0
2.5M	node_modules/ally.js
node_modules
└── ally.js
    ├── CHANGELOG.md
    ├── LICENSE.txt
    ├── README.md
    ├── ally.js
    ├── ally.js.map
    ├── ally.min.js
    ├── ally.min.js.map
    ├── amd
    ├── element
    ├── event
    ├── fix
    ├── get
    ├── is
    ├── maintain
    ├── map
    ├── node_modules
    ├── observe
    ├── package.json
    ├── prototype
    ├── query
    ├── selector
    ├── src
    ├── style
    ├── supports
    ├── util
    ├── version.js
    ├── version.js.map
    └── when

19 directories, 10 files
```

If bower would allow to point to an archive instead of a git-commitish™, we could provide the same files. But since it doesn't, you have to do it manually by referencing the archive hosted on github's release page.

However, if the ES6 source is just what you need, we may add a `bower.json` to get rid of `build`, `docs`. `test` and `tests`. This wouldn't reduce the amount of data you *download*, but what's being kept on the disk would shrink to 472K.

**Comment by jmacqueen** [comment]
I'm annoyed that ally.js didn't show up on bower's site when I did the search!

All I should need is the ES6 source. I pulled the ES6 source version into my project with `"ally.js": "1.0.1"` and tried the import...it balks on `fix/pointer-focus-children` with the import of `platform`. Which makes me sad.

Keeping all 4 dependency sources in sync and imported into the ember-cli structure is probably more effort than it's worth, so I think I'm stuck with referencing the archive via bower for now...at least until the npm path becomes a viable approach. Of course, it's possible I'm just missing something that'll make it all tick. I'll play with it some more later. Maybe something will come to me over the holiday.

**Comment by rodneyrehm** [comment]
> I'm annoyed that ally.js didn't show up on bower's site when I did the search!

maybe because I removed the bower.json a while back?

> … .it balks on `fix/pointer-focus-children` with the import of `platform`. Which makes me sad.

Because ally.js does currently not have a bower.json, no dependencies get downloaded. For 1.0.1 you need:

```
bower install array.prototype.findindex
bower install mathiasbynens/CSS.escape
bower install platform
```

> Keeping all 4 dependency sources in sync and imported into the ember-cli structure is probably more effort than it's worth

would adding back the bower.json help with that?

**Comment by jmacqueen** [comment]
I honestly don't know how much that would help. Inserting these guys into the build process to get imported and transpiled would be tricky, but may well be worth the effort. I'll take a stab at it (either today or in January) and let you know.

**Comment by jmacqueen** [comment]
Too many problems! I can get the individual dependencies into the ember-cli asset structure, `array.prototype.findIndex` wants to register as either `array.prototype.findindex/index` or `index` (based on the filename of the included file...and I can't figure out how to get `broccoli-funnel` to change the filename on copying over from `bower_components`) and `CSS.escape()` thinks it's in a Node environment and pukes because `module is not defined`.

<sigh> I have to get back to my main task now. For now, I'll stick with the archive reference and hope that progress on leveraging `npm` in ember-cli is made sooner rather than later :smile:

**Comment by rodneyrehm** [comment]
Thanks for checking it out! And thanks for providing the binding! I'll keep this issue open until we created a "known integrations" page.

> For now, I'll stick with the archive reference and hope that progress on leveraging `npm` in ember-cli is made sooner rather than later

Until then, do you have a way of getting pinged on new releases? we announce them on twitter ([@allyjs_io](https://twitter.com/allyjs_io)). Or you could use [sibbell](https://sibbell.com/about/) to get pinged of new github releases of your star-ed repos…

**Comment by jmacqueen** [comment]
Ooo. Sibbell is neat. All set up and ready to roll!
