### ISSUE TITLE
Code spans breaking in documentation on mobile 

### ISSUE THREAD

**Issue by FranzSkuffka** [medialize/ally.js#98]
The code spans are close to unreadable on mobile android browser. See screenshot  in attached link:
https://mega.nz/#!SB9HED5Z!I9uQgcvYt3qxxyJ9s5BSrXWxqbE6uwKfnWQzK_FBbiM

**Comment by rodneyrehm** [comment]
image not found…

**Comment by FranzSkuffka** [comment]
sorry, I assumed it was public
file:///tmp/mozilla_mozillaUser0/S51224-081116.jpg

**Comment by rodneyrehm** [comment]
Looks fine in Chrome Mobile… Not sure I even have an old Android stock Browser anywhere to debug this…

**Comment by FranzSkuffka** [comment]
Ok then :sob:
